Added simple test for documentation

diff --git a/.github/workflows/test-docker-stack.yml b/.github/workflows/test-docker-stack.yml
--- a/.github/workflows/test-docker-stack.yml
+++ b/.github/workflows/test-docker-stack.yml
@@ -15,37 +15,46 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v1
+    # Setup environment
+      - name: Checkout
+        uses: actions/checkout@v1
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
-    - name: Expose GitHub Runtime
-      uses: crazy-max/ghaction-github-runtime@v2
+      - name: Expose GitHub Runtime
+        uses: crazy-max/ghaction-github-runtime@v2
+
+    # Build and tag images  
+      - name: Build containers with cache
+        run : |
+          docker buildx bake \
+          --load \
+          --set=*.cache-from=type=gha \
+          --set=*.cache-to=type=gha
+
+      - name: Add tags to containers
+        run: docker compose --env-file=dev.env build
+
+    # Start Containers
+      - name: Start containers
+        run: docker compose --env-file=dev.env up -d
+
+    # Test API
+      - name: Install python dependencies
+        run: pip install -r requirements.txt
     
-    - name: Build containers with cache
-      run : |
-        docker buildx bake \
-        --load \
-        --set=*.cache-from=type=gha \
-        --set=*.cache-to=type=gha
+      - name: Run pytest
+        run: pytest ./api
 
-    - name: Add tags to containers
-      run: docker compose --env-file=dev.env build
+      - name: Run flake8
+        run: flake8 ./api
+        
+    # Test documentation
+      - name: Check if documentation is reachable
+        run: curl -f http://localhost:8001 || exit 1
 
-    - name: Start containers
-      run: docker compose --env-file=dev.env up -d
-
-    - name: Install python dependencies
-      run: pip install -r requirements.txt
-
-    - name: Run pytest
-      run: pytest ./api
-
-    - name: Run flake8
-      run: flake8 ./api
-
-    - name: Stop containers
-      if: always()
-      run: docker compose --env-file=dev.env down -v
+    # Clean up
+      - name: Stop containers
+        if: always()
+        run: docker compose --env-file=dev.env down -v
